export const CLUB_CATALOG = [
  {
    competition: "Liga Nacional / Liga Próximo",
    clubs: [
      "Argentino de Junín",
      "Atenas de Córdoba",
      "Boca Juniors",
      "Ferro Carril Oeste",
      "Gimnasia y Esgrima de Comodoro Rivadavia",
      "Independiente de Oliva",
      "Instituto de Córdoba",
      "La Unión de Formosa",
      "Oberá Tenis Club",
      "Obras Basket",
      "Olímpico de La Banda",
      "Peñarol de Mar del Plata",
      "Platense",
      "Quimsa",
      "Racing de Chivilcoy",
      "Regatas Corrientes",
      "San Lorenzo de Almagro",
      "San Martín de Corrientes",
      "Unión de Santa Fe",
    ],
  },
  {
    competition: "Liga Argentina",
    clubs: [
      "Amancay de La Rioja",
      "Atlético San Isidro",
      "Barrio Parque",
      "Bochas Sport Club",
      "Centenario de Venado Tuerto",
      "Central Entrerriano",
      "Comunicaciones de Mercedes",
      "Club Atlético Estudiantes de Tucumán",
      "Ciclista Juninense",
      "Colón de Santa Fe",
      "Deportivo Norte",
      "Deportivo Viedma",
      "El Talar",
      "Fusión Riojana",
      "Gimnasia y Esgrima de La Plata",
      "Hindú Club",
      "Huracán Las Heras",
      "Independiente BBC",
      "Jujuy Básquet",
      "La Unión de Colón",
      "Lanús",
      "Pergamino Básquet",
      "Pico Football Club",
      "Provincial de Rosario",
      "Quilmes de Mar del Plata",
      "Racing de Avellaneda",
      "Rivadavia Básquet",
      "Salta Basket",
      "Santa Paula de Gálvez",
      "Sportivo Suardi",
      "Tomás de Rocamora",
      "Unión de Mar del Plata",
      "Villa Mitre de Bahía Blanca",
      "Villa San Martín de Resistencia",
    ],
  },
  {
    competition: "Liga Federal",
    clubs: [
      "9 de Julio de Morteros",
      "Alejandro Korn",
      "All Boys de Santa Rosa",
      "Alma Juniors de Esperanza",
      "Almagro de Esperanza",
      "APV",
      "Argentino de Marcos Juárez",
      "Asociación Mitre",
      "Atenas de La Plata",
      "Atlético de Rafaela",
      "Atlético Regina",
      "Atlético Sastre",
      "Atlético Tostado",
      "Banda Norte",
      "Belgrano Cultural y Deportivo",
      "Belgrano de San Nicolás",
      "Bochas Sport Club",
      "CAPRI de Posadas",
      "Casa de Padua",
      "Caza y Pesca",
      "Centro Español de Plottier",
      "CEPA",
      "Ciudad de Campana",
      "Claridad",
      "Club Atlético Pilar",
      "Concepción BB",
      "Córdoba de Corrientes",
      "Cultural de Santa Sylvina",
      "Deportivo Plottier",
      "Deportivo Roca",
      "Don Bosco de Resistencia",
      "El Carmen de Perico",
      "El Ceibo",
      "Estudiantes de La Plata",
      "Estudiantes de Olavarría",
      "Estudiantil Porteño",
      "Ferro de General Pico",
      "GEVP",
      "Gimnasia y Esgrima de Ituzaingó",
      "Gimnasia y Esgrima de Rosario",
      "Gimnasia y Esgrima de Santa Fe",
      "Hércules de Charata",
      "Hindú Club de Resistencia",
      "Independiente de Avellaneda",
      "Independiente de General Pico",
      "Independiente de Neuquén",
      "Independiente de Tandil",
      "José Hernández",
      "La Armonía de Colón",
      "Los Indios de Moreno",
      "María Juana",
      "Matienzo de Córdoba",
      "Midland",
      "Mitre de Posadas",
      "Montmartre de Catamarca",
      "Morón",
      "Náutico Avellaneda",
      "Náutico Hacoaj",
      "Olimpia de Venado Tuerto",
      "Pacífico de Neuquén",
      "Pérfora de Plaza Huincul",
      "Petrolero Argentino de Plaza Huincul",
      "Pinocho",
      "Presidente Derqui",
      "Quique Club de Paraná",
      "Racing de Olavarría",
      "Red Star de Catamarca",
      "Regatas de Resistencia",
      "Regatas de San Nicolás",
      "Rivadavia Juniors de Santa Fe",
      "River Plate",
      "Rosario Central",
      "San Andrés",
      "San Fernando",
      "San Lorenzo de Monte Caseros",
      "San Martín de Marcos Juárez",
      "San Miguel",
      "Sanjustino",
      "Sionista",
      "Somisa de San Nicolás",
      "Sportivo Escobar",
      "Sportivo Pilar",
      "Sparta de Villa María",
      "Talleres de Tafí Viejo",
      "Temperley de Rosario",
      "Tokio de Posadas",
      "Tres de Febrero",
      "Unión de Oncativo",
      "Unión Central de Villa María",
      "Unión Vecinal de Munro",
      "Unión y Juventud de Bandera",
      "Urquiza de San Juan",
      "Urquiza de Santa Elena",
    ],
  },
  {
    competition: "Liga Metropolitana",
    clubs: [
      "Club Tres de Febrero",
      "Alejandro Korn",
      "Argentino de Castelar",
      "Asociación Vecinal de Pilar",
      "Berazategui",
      "Cañuelas Fútbol Club",
      "Caza y Pesca",
      "CEPA",
      "Claridad",
      "Defensores de Hurlingham",
      "Estudiantil Porteño",
      "Ezeiza",
      "Gimnasia y Esgrima de Ituzaingó",
      "Gimnasia y Esgrima de La Plata",
      "Las Heras de Villa Ballester",
      "Los Andes",
      "Los Indios de Moreno",
      "Midland",
      "Monte Grande",
      "Moreno de Quilmes",
      "Morón",
      "Náutico Hacoaj",
      "Nolting",
      "Casa de Padua",
      "Presidente Derqui",
      "San Andrés",
      "San Fernando",
      "San Miguel",
      "Sportivo Escobar",
      "Sportivo Pilar",
      "Unión Vecinal de Munro",
      "Universidad Nacional de La Matanza",
    ],
  },
  {
    competition: "Liga Femenina",
    clubs: [
      "Bochas Sport Club",
      "Chañares de James Craik",
      "Deportivo Berazategui",
      "El Biguá",
      "El Talar",
      "Ferro Carril Oeste",
      "Fusión Riojana",
      "Gorriones de Río Cuarto",
      "Hindú Club de Córdoba",
      "Independiente de Neuquén",
      "Instituto de Córdoba",
      "Lanús",
      "Náutico Sportivo Avellaneda",
      "Obras Basket",
      "Quimsa",
      "Tomás de Rocamora",
      "San José de Mendoza",
      "Unión Florida",
    ],
  },
] as const;

export const LIGA_ARGENTINA_OFFTUBE_CONTACTS = [
  "Ciclista Juninense",
  "Villa San Martín de Resistencia",
  "Huracán Las Heras",
  "Comunicaciones de Mercedes",
  "Tomás de Rocamora",
  "Rivadavia Básquet",
  "Pergamino Básquet",
  "La Unión de Colón",
  "Santa Paula de Gálvez",
  "Bochas Sport Club",
  "Club Atlético Estudiantes de Tucumán",
  "Centenario de Venado Tuerto",
  "Jujuy Básquet",
  "Central Entrerriano",
  "Salta Basket",
] as const;

export const ADDITIONAL_COMPETITIONS = [
  "ABB",
  "Amistosos",
  "BCLA",
  "Liga Desarrollo",
  "Liga Sudamericana Masc.",
  "Super 20",
  "Amistoso Selección Argentina",
  "Tour 3x3",
  "Metro 3x3",
  "Circuito 3x3",
  "La Liga 3x3",
  "Liga Metropolitana Fem",
  "Supercopa",
] as const;

export const CLUB_COMPETITIONS = Array.from(
  new Set([
    ...CLUB_CATALOG.map((entry) => entry.competition),
    ...ADDITIONAL_COMPETITIONS,
  ]),
);

// External leagues offered when creating/editing a team; they exist in the
// leagues table (0026/0037 migrations) but carry no club catalog of their own.
export const EXTERNAL_TEAM_LEAGUES = [
  "Liga Endesa (ACB)",
  "Liga BasquetPro (Ecuador)",
  "LNB Chile",
  "LUB (Uruguay)",
] as const;

export const ALL_CLUB_OPTIONS = Array.from(
  new Set([
    ...CLUB_CATALOG.flatMap((entry) => entry.clubs),
    ...LIGA_ARGENTINA_OFFTUBE_CONTACTS,
  ]),
);
