-- 0026: Seed leagues, clubs, teams and 2025/26 memberships; backfill matches.league_id.
-- Generated from src/lib/club-catalog.ts + src/lib/team-directory.ts overrides
-- and the competition strings observed in prod matches. Idempotent.

insert into public.leagues (name, slug, color, sort_order, is_external) values
  ('Liga Nacional', 'liga-nacional', '#e12121', 1, false),
  ('Liga Próximo', 'liga-proximo', '#2eac28', 2, false),
  ('Liga Argentina', 'liga-argentina', '#0a53a8', 3, false),
  ('Liga Federal', 'liga-federal', '#e8811a', 4, false),
  ('Liga Femenina', 'liga-femenina', '#c14588', 5, false),
  ('Liga Metropolitana', 'liga-metropolitana', '#5f78a7', 6, false),
  ('Liga Endesa (ACB)', 'liga-endesa-acb', '#c6dbe1', 20, true),
  ('Liga Italiana (LBA)', 'liga-italiana-lba', '#2b82d9', 21, true),
  ('Euroliga', 'euroliga', '#7bb824', 22, true),
  ('NBB', 'nbb', '#007520', 23, true),
  ('BCLA', 'bcla', '#00ffd0', 24, true),
  ('LPB Fem Ecuador', 'lpb-fem-ecuador', '#c076aa', 25, true),
  ('Interligas LDB', 'interligas-ldb', null, 26, true),
  ('Liga Chery', 'liga-chery', '#bfe1f6', 27, true),
  ('Exterior', 'exterior', '#ffcfc9', 28, true),
  ('Amistosos', 'amistosos', null, 30, false),
  ('3x3', '3x3', null, 31, false),
  ('Pre Metropolitana', 'pre-metropolitana', '#ffe5a0', 32, false)
on conflict (slug) do nothing;

insert into public.clubs (name, slug, stadium, website, instagram) values
  ('Argentino de Junín', 'argentino-de-junin', null, null, null),
  ('Atenas de Córdoba', 'atenas-de-cordoba', 'Estructuras Pretensa Atenas', 'https://www.atenas.com.ar/', 'https://www.instagram.com/atenascordobaoficial/'),
  ('Boca Juniors', 'boca-juniors', 'Luis Conde', 'https://www.bocajuniors.com.ar/', 'https://www.instagram.com/bocajrs/'),
  ('Ferro Carril Oeste', 'ferro-carril-oeste', null, null, null),
  ('Gimnasia y Esgrima de Comodoro Rivadavia', 'gimnasia-y-esgrima-de-comodoro-rivadavia', null, null, null),
  ('Independiente de Oliva', 'independiente-de-oliva', null, null, null),
  ('Instituto de Córdoba', 'instituto-de-cordoba', 'Ángel Sandrín', null, 'https://www.instagram.com/institutobasket/'),
  ('La Unión de Formosa', 'la-union-de-formosa', null, null, null),
  ('Oberá Tenis Club', 'obera-tenis-club', null, null, null),
  ('Obras Basket', 'obras-basket', 'El Templo del Rock', 'https://www.obrasbasket.com/', 'https://www.instagram.com/obrasbasket/'),
  ('Olímpico de La Banda', 'olimpico-de-la-banda', null, null, null),
  ('Peñarol de Mar del Plata', 'penarol-de-mar-del-plata', null, null, null),
  ('Platense', 'platense', null, null, null),
  ('Quimsa', 'quimsa', 'Ciudad', null, 'https://www.instagram.com/quimsabasquetoficial/'),
  ('Racing de Chivilcoy', 'racing-de-chivilcoy', null, null, null),
  ('Regatas Corrientes', 'regatas-corrientes', 'José Jorge Contte', null, 'https://www.instagram.com/regatasctes/'),
  ('San Lorenzo de Almagro', 'san-lorenzo-de-almagro', 'Pando', null, 'https://www.instagram.com/cslabasquet/'),
  ('San Martín de Corrientes', 'san-martin-de-corrientes', null, null, null),
  ('Unión de Santa Fe', 'union-de-santa-fe', 'Ángel Malvicino', null, null),
  ('Amancay de La Rioja', 'amancay-de-la-rioja', null, null, null),
  ('Atlético San Isidro', 'atletico-san-isidro', null, null, null),
  ('Barrio Parque', 'barrio-parque', null, null, null),
  ('Bochas Sport Club', 'bochas-sport-club', 'Bochas Sport Club', null, null),
  ('Centenario de Venado Tuerto', 'centenario-de-venado-tuerto', null, null, null),
  ('Central Entrerriano', 'central-entrerriano', null, null, null),
  ('Comunicaciones de Mercedes', 'comunicaciones-de-mercedes', null, null, null),
  ('Club Atlético Estudiantes de Tucumán', 'club-atletico-estudiantes-de-tucuman', null, null, null),
  ('Ciclista Juninense', 'ciclista-juninense', null, null, null),
  ('Colón de Santa Fe', 'colon-de-santa-fe', null, null, null),
  ('Deportivo Norte', 'deportivo-norte', null, null, null),
  ('Deportivo Viedma', 'deportivo-viedma', null, null, null),
  ('El Talar', 'el-talar', null, null, null),
  ('Fusión Riojana', 'fusion-riojana', null, null, null),
  ('Gimnasia y Esgrima de La Plata', 'gimnasia-y-esgrima-de-la-plata', null, null, null),
  ('Hindú Club', 'hindu-club', null, null, null),
  ('Huracán Las Heras', 'huracan-las-heras', null, null, null),
  ('Independiente BBC', 'independiente-bbc', null, null, null),
  ('Jujuy Básquet', 'jujuy-basquet', null, null, null),
  ('La Unión de Colón', 'la-union-de-colon', null, null, null),
  ('Lanús', 'lanus', null, null, null),
  ('Pergamino Básquet', 'pergamino-basquet', 'Ricardo Dorado Merlo', null, null),
  ('Pico Football Club', 'pico-football-club', null, null, null),
  ('Provincial de Rosario', 'provincial-de-rosario', null, null, null),
  ('Quilmes de Mar del Plata', 'quilmes-de-mar-del-plata', null, null, null),
  ('Racing de Avellaneda', 'racing-de-avellaneda', null, null, null),
  ('Rivadavia Básquet', 'rivadavia-basquet', null, null, null),
  ('Salta Basket', 'salta-basket', null, null, null),
  ('Santa Paula de Gálvez', 'santa-paula-de-galvez', null, null, null),
  ('Sportivo Suardi', 'sportivo-suardi', null, null, null),
  ('Tomás de Rocamora', 'tomas-de-rocamora', null, null, null),
  ('Unión de Mar del Plata', 'union-de-mar-del-plata', null, null, null),
  ('Villa Mitre de Bahía Blanca', 'villa-mitre-de-bahia-blanca', null, null, null),
  ('Villa San Martín de Resistencia', 'villa-san-martin-de-resistencia', 'Villa San Martín', null, null),
  ('9 de Julio de Morteros', '9-de-julio-de-morteros', null, null, null),
  ('Alejandro Korn', 'alejandro-korn', null, null, null),
  ('All Boys de Santa Rosa', 'all-boys-de-santa-rosa', null, null, null),
  ('Alma Juniors de Esperanza', 'alma-juniors-de-esperanza', null, null, null),
  ('Almagro de Esperanza', 'almagro-de-esperanza', null, null, null),
  ('APV', 'apv', null, null, null),
  ('Argentino de Marcos Juárez', 'argentino-de-marcos-juarez', null, null, null),
  ('Asociación Mitre', 'asociacion-mitre', null, null, null),
  ('Atenas de La Plata', 'atenas-de-la-plata', null, null, null),
  ('Atlético de Rafaela', 'atletico-de-rafaela', null, null, null),
  ('Atlético Regina', 'atletico-regina', null, null, null),
  ('Atlético Sastre', 'atletico-sastre', null, null, null),
  ('Atlético Tostado', 'atletico-tostado', null, null, null),
  ('Banda Norte', 'banda-norte', null, null, null),
  ('Belgrano Cultural y Deportivo', 'belgrano-cultural-y-deportivo', null, null, null),
  ('Belgrano de San Nicolás', 'belgrano-de-san-nicolas', null, null, null),
  ('CAPRI de Posadas', 'capri-de-posadas', null, null, null),
  ('Casa de Padua', 'casa-de-padua', null, null, null),
  ('Caza y Pesca', 'caza-y-pesca', null, null, null),
  ('Centro Español de Plottier', 'centro-espanol-de-plottier', null, null, null),
  ('CEPA', 'cepa', null, null, null),
  ('Ciudad de Campana', 'ciudad-de-campana', null, null, null),
  ('Claridad', 'claridad', null, null, null),
  ('Club Atlético Pilar', 'club-atletico-pilar', null, null, null),
  ('Concepción BB', 'concepcion-bb', null, null, null),
  ('Córdoba de Corrientes', 'cordoba-de-corrientes', null, null, null),
  ('Cultural de Santa Sylvina', 'cultural-de-santa-sylvina', null, null, null),
  ('Deportivo Plottier', 'deportivo-plottier', null, null, null),
  ('Deportivo Roca', 'deportivo-roca', null, null, null),
  ('Don Bosco de Resistencia', 'don-bosco-de-resistencia', null, null, null),
  ('El Carmen de Perico', 'el-carmen-de-perico', null, null, null),
  ('El Ceibo', 'el-ceibo', null, null, null),
  ('Estudiantes de La Plata', 'estudiantes-de-la-plata', null, null, null),
  ('Estudiantes de Olavarría', 'estudiantes-de-olavarria', null, null, null),
  ('Estudiantil Porteño', 'estudiantil-porteno', null, null, null),
  ('Ferro de General Pico', 'ferro-de-general-pico', null, null, null),
  ('GEVP', 'gevp', null, null, null),
  ('Gimnasia y Esgrima de Ituzaingó', 'gimnasia-y-esgrima-de-ituzaingo', null, null, null),
  ('Gimnasia y Esgrima de Rosario', 'gimnasia-y-esgrima-de-rosario', null, null, null),
  ('Gimnasia y Esgrima de Santa Fe', 'gimnasia-y-esgrima-de-santa-fe', null, null, null),
  ('Hércules de Charata', 'hercules-de-charata', null, null, null),
  ('Hindú Club de Resistencia', 'hindu-club-de-resistencia', null, null, null),
  ('Independiente de Avellaneda', 'independiente-de-avellaneda', null, null, null),
  ('Independiente de General Pico', 'independiente-de-general-pico', null, null, null),
  ('Independiente de Neuquén', 'independiente-de-neuquen', null, null, null),
  ('Independiente de Tandil', 'independiente-de-tandil', null, null, null),
  ('José Hernández', 'jose-hernandez', null, null, null),
  ('La Armonía de Colón', 'la-armonia-de-colon', null, null, null),
  ('Los Indios de Moreno', 'los-indios-de-moreno', null, null, null),
  ('María Juana', 'maria-juana', null, null, null),
  ('Matienzo de Córdoba', 'matienzo-de-cordoba', null, null, null),
  ('Midland', 'midland', null, null, null),
  ('Mitre de Posadas', 'mitre-de-posadas', null, null, null),
  ('Montmartre de Catamarca', 'montmartre-de-catamarca', null, null, null),
  ('Morón', 'moron', null, null, null),
  ('Náutico Avellaneda', 'nautico-avellaneda', null, null, null),
  ('Náutico Hacoaj', 'nautico-hacoaj', null, null, null),
  ('Olimpia de Venado Tuerto', 'olimpia-de-venado-tuerto', null, null, null),
  ('Pacífico de Neuquén', 'pacifico-de-neuquen', null, null, null),
  ('Pérfora de Plaza Huincul', 'perfora-de-plaza-huincul', null, null, null),
  ('Petrolero Argentino de Plaza Huincul', 'petrolero-argentino-de-plaza-huincul', null, null, null),
  ('Pinocho', 'pinocho', null, null, null),
  ('Presidente Derqui', 'presidente-derqui', null, null, null),
  ('Quique Club de Paraná', 'quique-club-de-parana', null, null, null),
  ('Racing de Olavarría', 'racing-de-olavarria', null, null, null),
  ('Red Star de Catamarca', 'red-star-de-catamarca', null, null, null),
  ('Regatas de Resistencia', 'regatas-de-resistencia', null, null, null),
  ('Regatas de San Nicolás', 'regatas-de-san-nicolas', null, null, null),
  ('Rivadavia Juniors de Santa Fe', 'rivadavia-juniors-de-santa-fe', null, null, null),
  ('River Plate', 'river-plate', null, null, null),
  ('Rosario Central', 'rosario-central', null, null, null),
  ('San Andrés', 'san-andres', null, null, null),
  ('San Fernando', 'san-fernando', null, null, null),
  ('San Lorenzo de Monte Caseros', 'san-lorenzo-de-monte-caseros', null, null, null),
  ('San Martín de Marcos Juárez', 'san-martin-de-marcos-juarez', null, null, null),
  ('San Miguel', 'san-miguel', null, null, null),
  ('Sanjustino', 'sanjustino', null, null, null),
  ('Sionista', 'sionista', null, null, null),
  ('Somisa de San Nicolás', 'somisa-de-san-nicolas', null, null, null),
  ('Sportivo Escobar', 'sportivo-escobar', null, null, null),
  ('Sportivo Pilar', 'sportivo-pilar', null, null, null),
  ('Sparta de Villa María', 'sparta-de-villa-maria', null, null, null),
  ('Talleres de Tafí Viejo', 'talleres-de-tafi-viejo', null, null, null),
  ('Temperley de Rosario', 'temperley-de-rosario', null, null, null),
  ('Tokio de Posadas', 'tokio-de-posadas', null, null, null),
  ('Tres de Febrero', 'tres-de-febrero', null, null, null),
  ('Unión de Oncativo', 'union-de-oncativo', null, null, null),
  ('Unión Central de Villa María', 'union-central-de-villa-maria', null, null, null),
  ('Unión Vecinal de Munro', 'union-vecinal-de-munro', null, null, null),
  ('Unión y Juventud de Bandera', 'union-y-juventud-de-bandera', null, null, null),
  ('Urquiza de San Juan', 'urquiza-de-san-juan', null, null, null),
  ('Urquiza de Santa Elena', 'urquiza-de-santa-elena', null, null, null),
  ('Club Tres de Febrero', 'club-tres-de-febrero', null, null, null),
  ('Argentino de Castelar', 'argentino-de-castelar', null, null, null),
  ('Asociación Vecinal de Pilar', 'asociacion-vecinal-de-pilar', null, null, null),
  ('Berazategui', 'berazategui', null, null, null),
  ('Cañuelas Fútbol Club', 'canuelas-futbol-club', null, null, null),
  ('Defensores de Hurlingham', 'defensores-de-hurlingham', null, null, null),
  ('Ezeiza', 'ezeiza', null, null, null),
  ('Las Heras de Villa Ballester', 'las-heras-de-villa-ballester', null, null, null),
  ('Los Andes', 'los-andes', null, null, null),
  ('Monte Grande', 'monte-grande', null, null, null),
  ('Moreno de Quilmes', 'moreno-de-quilmes', null, null, null),
  ('Nolting', 'nolting', null, null, null),
  ('Universidad Nacional de La Matanza', 'universidad-nacional-de-la-matanza', null, null, null),
  ('Chañares de James Craik', 'chanares-de-james-craik', null, null, null),
  ('Deportivo Berazategui', 'deportivo-berazategui', null, null, null),
  ('El Biguá', 'el-bigua', null, null, null),
  ('Gorriones de Río Cuarto', 'gorriones-de-rio-cuarto', null, null, null),
  ('Hindú Club de Córdoba', 'hindu-club-de-cordoba', null, null, null),
  ('Náutico Sportivo Avellaneda', 'nautico-sportivo-avellaneda', null, null, null),
  ('San José de Mendoza', 'san-jose-de-mendoza', null, null, null),
  ('Unión Florida', 'union-florida', null, null, null)
on conflict (slug) do nothing;

insert into public.teams (club_id, name, slug, category)
select c.id, v.team_name, v.team_slug, v.category
from (values
  ('argentino-de-junin', 'Argentino de Junín', 'argentino-de-junin', 'mayores'),
  ('argentino-de-junin', 'Argentino de Junín', 'argentino-de-junin-proximo', 'proximo'),
  ('atenas-de-cordoba', 'Atenas de Córdoba', 'atenas-de-cordoba', 'mayores'),
  ('atenas-de-cordoba', 'Atenas de Córdoba', 'atenas-de-cordoba-proximo', 'proximo'),
  ('boca-juniors', 'Boca Juniors', 'boca-juniors', 'mayores'),
  ('boca-juniors', 'Boca Juniors', 'boca-juniors-proximo', 'proximo'),
  ('ferro-carril-oeste', 'Ferro Carril Oeste', 'ferro-carril-oeste', 'mayores'),
  ('ferro-carril-oeste', 'Ferro Carril Oeste', 'ferro-carril-oeste-proximo', 'proximo'),
  ('gimnasia-y-esgrima-de-comodoro-rivadavia', 'Gimnasia y Esgrima de Comodoro Rivadavia', 'gimnasia-y-esgrima-de-comodoro-rivadavia', 'mayores'),
  ('gimnasia-y-esgrima-de-comodoro-rivadavia', 'Gimnasia y Esgrima de Comodoro Rivadavia', 'gimnasia-y-esgrima-de-comodoro-rivadavia-proximo', 'proximo'),
  ('independiente-de-oliva', 'Independiente de Oliva', 'independiente-de-oliva', 'mayores'),
  ('independiente-de-oliva', 'Independiente de Oliva', 'independiente-de-oliva-proximo', 'proximo'),
  ('instituto-de-cordoba', 'Instituto de Córdoba', 'instituto-de-cordoba', 'mayores'),
  ('instituto-de-cordoba', 'Instituto de Córdoba', 'instituto-de-cordoba-proximo', 'proximo'),
  ('la-union-de-formosa', 'La Unión de Formosa', 'la-union-de-formosa', 'mayores'),
  ('la-union-de-formosa', 'La Unión de Formosa', 'la-union-de-formosa-proximo', 'proximo'),
  ('obera-tenis-club', 'Oberá Tenis Club', 'obera-tenis-club', 'mayores'),
  ('obera-tenis-club', 'Oberá Tenis Club', 'obera-tenis-club-proximo', 'proximo'),
  ('obras-basket', 'Obras Basket', 'obras-basket', 'mayores'),
  ('obras-basket', 'Obras Basket', 'obras-basket-proximo', 'proximo'),
  ('olimpico-de-la-banda', 'Olímpico de La Banda', 'olimpico-de-la-banda', 'mayores'),
  ('olimpico-de-la-banda', 'Olímpico de La Banda', 'olimpico-de-la-banda-proximo', 'proximo'),
  ('penarol-de-mar-del-plata', 'Peñarol de Mar del Plata', 'penarol-de-mar-del-plata', 'mayores'),
  ('penarol-de-mar-del-plata', 'Peñarol de Mar del Plata', 'penarol-de-mar-del-plata-proximo', 'proximo'),
  ('platense', 'Platense', 'platense', 'mayores'),
  ('platense', 'Platense', 'platense-proximo', 'proximo'),
  ('quimsa', 'Quimsa', 'quimsa', 'mayores'),
  ('quimsa', 'Quimsa', 'quimsa-proximo', 'proximo'),
  ('racing-de-chivilcoy', 'Racing de Chivilcoy', 'racing-de-chivilcoy', 'mayores'),
  ('racing-de-chivilcoy', 'Racing de Chivilcoy', 'racing-de-chivilcoy-proximo', 'proximo'),
  ('regatas-corrientes', 'Regatas Corrientes', 'regatas-corrientes', 'mayores'),
  ('regatas-corrientes', 'Regatas Corrientes', 'regatas-corrientes-proximo', 'proximo'),
  ('san-lorenzo-de-almagro', 'San Lorenzo de Almagro', 'san-lorenzo-de-almagro', 'mayores'),
  ('san-lorenzo-de-almagro', 'San Lorenzo de Almagro', 'san-lorenzo-de-almagro-proximo', 'proximo'),
  ('san-martin-de-corrientes', 'San Martín de Corrientes', 'san-martin-de-corrientes', 'mayores'),
  ('san-martin-de-corrientes', 'San Martín de Corrientes', 'san-martin-de-corrientes-proximo', 'proximo'),
  ('union-de-santa-fe', 'Unión de Santa Fe', 'union-de-santa-fe', 'mayores'),
  ('union-de-santa-fe', 'Unión de Santa Fe', 'union-de-santa-fe-proximo', 'proximo'),
  ('amancay-de-la-rioja', 'Amancay de La Rioja', 'amancay-de-la-rioja', 'mayores'),
  ('atletico-san-isidro', 'Atlético San Isidro', 'atletico-san-isidro', 'mayores'),
  ('barrio-parque', 'Barrio Parque', 'barrio-parque', 'mayores'),
  ('bochas-sport-club', 'Bochas Sport Club', 'bochas-sport-club', 'mayores'),
  ('centenario-de-venado-tuerto', 'Centenario de Venado Tuerto', 'centenario-de-venado-tuerto', 'mayores'),
  ('central-entrerriano', 'Central Entrerriano', 'central-entrerriano', 'mayores'),
  ('comunicaciones-de-mercedes', 'Comunicaciones de Mercedes', 'comunicaciones-de-mercedes', 'mayores'),
  ('club-atletico-estudiantes-de-tucuman', 'Club Atlético Estudiantes de Tucumán', 'club-atletico-estudiantes-de-tucuman', 'mayores'),
  ('ciclista-juninense', 'Ciclista Juninense', 'ciclista-juninense', 'mayores'),
  ('colon-de-santa-fe', 'Colón de Santa Fe', 'colon-de-santa-fe', 'mayores'),
  ('deportivo-norte', 'Deportivo Norte', 'deportivo-norte', 'mayores'),
  ('deportivo-viedma', 'Deportivo Viedma', 'deportivo-viedma', 'mayores'),
  ('el-talar', 'El Talar', 'el-talar', 'mayores'),
  ('fusion-riojana', 'Fusión Riojana', 'fusion-riojana', 'mayores'),
  ('gimnasia-y-esgrima-de-la-plata', 'Gimnasia y Esgrima de La Plata', 'gimnasia-y-esgrima-de-la-plata', 'mayores'),
  ('hindu-club', 'Hindú Club', 'hindu-club', 'mayores'),
  ('huracan-las-heras', 'Huracán Las Heras', 'huracan-las-heras', 'mayores'),
  ('independiente-bbc', 'Independiente BBC', 'independiente-bbc', 'mayores'),
  ('jujuy-basquet', 'Jujuy Básquet', 'jujuy-basquet', 'mayores'),
  ('la-union-de-colon', 'La Unión de Colón', 'la-union-de-colon', 'mayores'),
  ('lanus', 'Lanús', 'lanus', 'mayores'),
  ('pergamino-basquet', 'Pergamino Básquet', 'pergamino-basquet', 'mayores'),
  ('pico-football-club', 'Pico Football Club', 'pico-football-club', 'mayores'),
  ('provincial-de-rosario', 'Provincial de Rosario', 'provincial-de-rosario', 'mayores'),
  ('quilmes-de-mar-del-plata', 'Quilmes de Mar del Plata', 'quilmes-de-mar-del-plata', 'mayores'),
  ('racing-de-avellaneda', 'Racing de Avellaneda', 'racing-de-avellaneda', 'mayores'),
  ('rivadavia-basquet', 'Rivadavia Básquet', 'rivadavia-basquet', 'mayores'),
  ('salta-basket', 'Salta Basket', 'salta-basket', 'mayores'),
  ('santa-paula-de-galvez', 'Santa Paula de Gálvez', 'santa-paula-de-galvez', 'mayores'),
  ('sportivo-suardi', 'Sportivo Suardi', 'sportivo-suardi', 'mayores'),
  ('tomas-de-rocamora', 'Tomás de Rocamora', 'tomas-de-rocamora', 'mayores'),
  ('union-de-mar-del-plata', 'Unión de Mar del Plata', 'union-de-mar-del-plata', 'mayores'),
  ('villa-mitre-de-bahia-blanca', 'Villa Mitre de Bahía Blanca', 'villa-mitre-de-bahia-blanca', 'mayores'),
  ('villa-san-martin-de-resistencia', 'Villa San Martín de Resistencia', 'villa-san-martin-de-resistencia', 'mayores'),
  ('9-de-julio-de-morteros', '9 de Julio de Morteros', '9-de-julio-de-morteros', 'mayores'),
  ('alejandro-korn', 'Alejandro Korn', 'alejandro-korn', 'mayores'),
  ('all-boys-de-santa-rosa', 'All Boys de Santa Rosa', 'all-boys-de-santa-rosa', 'mayores'),
  ('alma-juniors-de-esperanza', 'Alma Juniors de Esperanza', 'alma-juniors-de-esperanza', 'mayores'),
  ('almagro-de-esperanza', 'Almagro de Esperanza', 'almagro-de-esperanza', 'mayores'),
  ('apv', 'APV', 'apv', 'mayores'),
  ('argentino-de-marcos-juarez', 'Argentino de Marcos Juárez', 'argentino-de-marcos-juarez', 'mayores'),
  ('asociacion-mitre', 'Asociación Mitre', 'asociacion-mitre', 'mayores'),
  ('atenas-de-la-plata', 'Atenas de La Plata', 'atenas-de-la-plata', 'mayores'),
  ('atletico-de-rafaela', 'Atlético de Rafaela', 'atletico-de-rafaela', 'mayores'),
  ('atletico-regina', 'Atlético Regina', 'atletico-regina', 'mayores'),
  ('atletico-sastre', 'Atlético Sastre', 'atletico-sastre', 'mayores'),
  ('atletico-tostado', 'Atlético Tostado', 'atletico-tostado', 'mayores'),
  ('banda-norte', 'Banda Norte', 'banda-norte', 'mayores'),
  ('belgrano-cultural-y-deportivo', 'Belgrano Cultural y Deportivo', 'belgrano-cultural-y-deportivo', 'mayores'),
  ('belgrano-de-san-nicolas', 'Belgrano de San Nicolás', 'belgrano-de-san-nicolas', 'mayores'),
  ('capri-de-posadas', 'CAPRI de Posadas', 'capri-de-posadas', 'mayores'),
  ('casa-de-padua', 'Casa de Padua', 'casa-de-padua', 'mayores'),
  ('caza-y-pesca', 'Caza y Pesca', 'caza-y-pesca', 'mayores'),
  ('centro-espanol-de-plottier', 'Centro Español de Plottier', 'centro-espanol-de-plottier', 'mayores'),
  ('cepa', 'CEPA', 'cepa', 'mayores'),
  ('ciudad-de-campana', 'Ciudad de Campana', 'ciudad-de-campana', 'mayores'),
  ('claridad', 'Claridad', 'claridad', 'mayores'),
  ('club-atletico-pilar', 'Club Atlético Pilar', 'club-atletico-pilar', 'mayores'),
  ('concepcion-bb', 'Concepción BB', 'concepcion-bb', 'mayores'),
  ('cordoba-de-corrientes', 'Córdoba de Corrientes', 'cordoba-de-corrientes', 'mayores'),
  ('cultural-de-santa-sylvina', 'Cultural de Santa Sylvina', 'cultural-de-santa-sylvina', 'mayores'),
  ('deportivo-plottier', 'Deportivo Plottier', 'deportivo-plottier', 'mayores'),
  ('deportivo-roca', 'Deportivo Roca', 'deportivo-roca', 'mayores'),
  ('don-bosco-de-resistencia', 'Don Bosco de Resistencia', 'don-bosco-de-resistencia', 'mayores'),
  ('el-carmen-de-perico', 'El Carmen de Perico', 'el-carmen-de-perico', 'mayores'),
  ('el-ceibo', 'El Ceibo', 'el-ceibo', 'mayores'),
  ('estudiantes-de-la-plata', 'Estudiantes de La Plata', 'estudiantes-de-la-plata', 'mayores'),
  ('estudiantes-de-olavarria', 'Estudiantes de Olavarría', 'estudiantes-de-olavarria', 'mayores'),
  ('estudiantil-porteno', 'Estudiantil Porteño', 'estudiantil-porteno', 'mayores'),
  ('ferro-de-general-pico', 'Ferro de General Pico', 'ferro-de-general-pico', 'mayores'),
  ('gevp', 'GEVP', 'gevp', 'mayores'),
  ('gimnasia-y-esgrima-de-ituzaingo', 'Gimnasia y Esgrima de Ituzaingó', 'gimnasia-y-esgrima-de-ituzaingo', 'mayores'),
  ('gimnasia-y-esgrima-de-rosario', 'Gimnasia y Esgrima de Rosario', 'gimnasia-y-esgrima-de-rosario', 'mayores'),
  ('gimnasia-y-esgrima-de-santa-fe', 'Gimnasia y Esgrima de Santa Fe', 'gimnasia-y-esgrima-de-santa-fe', 'mayores'),
  ('hercules-de-charata', 'Hércules de Charata', 'hercules-de-charata', 'mayores'),
  ('hindu-club-de-resistencia', 'Hindú Club de Resistencia', 'hindu-club-de-resistencia', 'mayores'),
  ('independiente-de-avellaneda', 'Independiente de Avellaneda', 'independiente-de-avellaneda', 'mayores'),
  ('independiente-de-general-pico', 'Independiente de General Pico', 'independiente-de-general-pico', 'mayores'),
  ('independiente-de-neuquen', 'Independiente de Neuquén', 'independiente-de-neuquen', 'mayores'),
  ('independiente-de-tandil', 'Independiente de Tandil', 'independiente-de-tandil', 'mayores'),
  ('jose-hernandez', 'José Hernández', 'jose-hernandez', 'mayores'),
  ('la-armonia-de-colon', 'La Armonía de Colón', 'la-armonia-de-colon', 'mayores'),
  ('los-indios-de-moreno', 'Los Indios de Moreno', 'los-indios-de-moreno', 'mayores'),
  ('maria-juana', 'María Juana', 'maria-juana', 'mayores'),
  ('matienzo-de-cordoba', 'Matienzo de Córdoba', 'matienzo-de-cordoba', 'mayores'),
  ('midland', 'Midland', 'midland', 'mayores'),
  ('mitre-de-posadas', 'Mitre de Posadas', 'mitre-de-posadas', 'mayores'),
  ('montmartre-de-catamarca', 'Montmartre de Catamarca', 'montmartre-de-catamarca', 'mayores'),
  ('moron', 'Morón', 'moron', 'mayores'),
  ('nautico-avellaneda', 'Náutico Avellaneda', 'nautico-avellaneda', 'mayores'),
  ('nautico-hacoaj', 'Náutico Hacoaj', 'nautico-hacoaj', 'mayores'),
  ('olimpia-de-venado-tuerto', 'Olimpia de Venado Tuerto', 'olimpia-de-venado-tuerto', 'mayores'),
  ('pacifico-de-neuquen', 'Pacífico de Neuquén', 'pacifico-de-neuquen', 'mayores'),
  ('perfora-de-plaza-huincul', 'Pérfora de Plaza Huincul', 'perfora-de-plaza-huincul', 'mayores'),
  ('petrolero-argentino-de-plaza-huincul', 'Petrolero Argentino de Plaza Huincul', 'petrolero-argentino-de-plaza-huincul', 'mayores'),
  ('pinocho', 'Pinocho', 'pinocho', 'mayores'),
  ('presidente-derqui', 'Presidente Derqui', 'presidente-derqui', 'mayores'),
  ('quique-club-de-parana', 'Quique Club de Paraná', 'quique-club-de-parana', 'mayores'),
  ('racing-de-olavarria', 'Racing de Olavarría', 'racing-de-olavarria', 'mayores'),
  ('red-star-de-catamarca', 'Red Star de Catamarca', 'red-star-de-catamarca', 'mayores'),
  ('regatas-de-resistencia', 'Regatas de Resistencia', 'regatas-de-resistencia', 'mayores'),
  ('regatas-de-san-nicolas', 'Regatas de San Nicolás', 'regatas-de-san-nicolas', 'mayores'),
  ('rivadavia-juniors-de-santa-fe', 'Rivadavia Juniors de Santa Fe', 'rivadavia-juniors-de-santa-fe', 'mayores'),
  ('river-plate', 'River Plate', 'river-plate', 'mayores'),
  ('rosario-central', 'Rosario Central', 'rosario-central', 'mayores'),
  ('san-andres', 'San Andrés', 'san-andres', 'mayores'),
  ('san-fernando', 'San Fernando', 'san-fernando', 'mayores'),
  ('san-lorenzo-de-monte-caseros', 'San Lorenzo de Monte Caseros', 'san-lorenzo-de-monte-caseros', 'mayores'),
  ('san-martin-de-marcos-juarez', 'San Martín de Marcos Juárez', 'san-martin-de-marcos-juarez', 'mayores'),
  ('san-miguel', 'San Miguel', 'san-miguel', 'mayores'),
  ('sanjustino', 'Sanjustino', 'sanjustino', 'mayores'),
  ('sionista', 'Sionista', 'sionista', 'mayores'),
  ('somisa-de-san-nicolas', 'Somisa de San Nicolás', 'somisa-de-san-nicolas', 'mayores'),
  ('sportivo-escobar', 'Sportivo Escobar', 'sportivo-escobar', 'mayores'),
  ('sportivo-pilar', 'Sportivo Pilar', 'sportivo-pilar', 'mayores'),
  ('sparta-de-villa-maria', 'Sparta de Villa María', 'sparta-de-villa-maria', 'mayores'),
  ('talleres-de-tafi-viejo', 'Talleres de Tafí Viejo', 'talleres-de-tafi-viejo', 'mayores'),
  ('temperley-de-rosario', 'Temperley de Rosario', 'temperley-de-rosario', 'mayores'),
  ('tokio-de-posadas', 'Tokio de Posadas', 'tokio-de-posadas', 'mayores'),
  ('tres-de-febrero', 'Tres de Febrero', 'tres-de-febrero', 'mayores'),
  ('union-de-oncativo', 'Unión de Oncativo', 'union-de-oncativo', 'mayores'),
  ('union-central-de-villa-maria', 'Unión Central de Villa María', 'union-central-de-villa-maria', 'mayores'),
  ('union-vecinal-de-munro', 'Unión Vecinal de Munro', 'union-vecinal-de-munro', 'mayores'),
  ('union-y-juventud-de-bandera', 'Unión y Juventud de Bandera', 'union-y-juventud-de-bandera', 'mayores'),
  ('urquiza-de-san-juan', 'Urquiza de San Juan', 'urquiza-de-san-juan', 'mayores'),
  ('urquiza-de-santa-elena', 'Urquiza de Santa Elena', 'urquiza-de-santa-elena', 'mayores'),
  ('club-tres-de-febrero', 'Club Tres de Febrero', 'club-tres-de-febrero', 'mayores'),
  ('argentino-de-castelar', 'Argentino de Castelar', 'argentino-de-castelar', 'mayores'),
  ('asociacion-vecinal-de-pilar', 'Asociación Vecinal de Pilar', 'asociacion-vecinal-de-pilar', 'mayores'),
  ('berazategui', 'Berazategui', 'berazategui', 'mayores'),
  ('canuelas-futbol-club', 'Cañuelas Fútbol Club', 'canuelas-futbol-club', 'mayores'),
  ('defensores-de-hurlingham', 'Defensores de Hurlingham', 'defensores-de-hurlingham', 'mayores'),
  ('ezeiza', 'Ezeiza', 'ezeiza', 'mayores'),
  ('las-heras-de-villa-ballester', 'Las Heras de Villa Ballester', 'las-heras-de-villa-ballester', 'mayores'),
  ('los-andes', 'Los Andes', 'los-andes', 'mayores'),
  ('monte-grande', 'Monte Grande', 'monte-grande', 'mayores'),
  ('moreno-de-quilmes', 'Moreno de Quilmes', 'moreno-de-quilmes', 'mayores'),
  ('nolting', 'Nolting', 'nolting', 'mayores'),
  ('universidad-nacional-de-la-matanza', 'Universidad Nacional de La Matanza', 'universidad-nacional-de-la-matanza', 'mayores'),
  ('bochas-sport-club', 'Bochas Sport Club', 'bochas-sport-club-femenino', 'femenino'),
  ('chanares-de-james-craik', 'Chañares de James Craik', 'chanares-de-james-craik-femenino', 'femenino'),
  ('deportivo-berazategui', 'Deportivo Berazategui', 'deportivo-berazategui-femenino', 'femenino'),
  ('el-bigua', 'El Biguá', 'el-bigua-femenino', 'femenino'),
  ('el-talar', 'El Talar', 'el-talar-femenino', 'femenino'),
  ('ferro-carril-oeste', 'Ferro Carril Oeste', 'ferro-carril-oeste-femenino', 'femenino'),
  ('fusion-riojana', 'Fusión Riojana', 'fusion-riojana-femenino', 'femenino'),
  ('gorriones-de-rio-cuarto', 'Gorriones de Río Cuarto', 'gorriones-de-rio-cuarto-femenino', 'femenino'),
  ('hindu-club-de-cordoba', 'Hindú Club de Córdoba', 'hindu-club-de-cordoba-femenino', 'femenino'),
  ('independiente-de-neuquen', 'Independiente de Neuquén', 'independiente-de-neuquen-femenino', 'femenino'),
  ('instituto-de-cordoba', 'Instituto de Córdoba', 'instituto-de-cordoba-femenino', 'femenino'),
  ('lanus', 'Lanús', 'lanus-femenino', 'femenino'),
  ('nautico-sportivo-avellaneda', 'Náutico Sportivo Avellaneda', 'nautico-sportivo-avellaneda-femenino', 'femenino'),
  ('obras-basket', 'Obras Basket', 'obras-basket-femenino', 'femenino'),
  ('quimsa', 'Quimsa', 'quimsa-femenino', 'femenino'),
  ('tomas-de-rocamora', 'Tomás de Rocamora', 'tomas-de-rocamora-femenino', 'femenino'),
  ('san-jose-de-mendoza', 'San José de Mendoza', 'san-jose-de-mendoza-femenino', 'femenino'),
  ('union-florida', 'Unión Florida', 'union-florida-femenino', 'femenino')
) as v(club_slug, team_name, team_slug, category)
join public.clubs c on c.slug = v.club_slug
on conflict (slug) do nothing;

insert into public.team_league_memberships (team_id, league_id, season)
select t.id, l.id, '2025/26'
from (values
  ('argentino-de-junin', 'liga-nacional'),
  ('argentino-de-junin-proximo', 'liga-proximo'),
  ('atenas-de-cordoba', 'liga-nacional'),
  ('atenas-de-cordoba-proximo', 'liga-proximo'),
  ('boca-juniors', 'liga-nacional'),
  ('boca-juniors-proximo', 'liga-proximo'),
  ('ferro-carril-oeste', 'liga-nacional'),
  ('ferro-carril-oeste-proximo', 'liga-proximo'),
  ('gimnasia-y-esgrima-de-comodoro-rivadavia', 'liga-nacional'),
  ('gimnasia-y-esgrima-de-comodoro-rivadavia-proximo', 'liga-proximo'),
  ('independiente-de-oliva', 'liga-nacional'),
  ('independiente-de-oliva-proximo', 'liga-proximo'),
  ('instituto-de-cordoba', 'liga-nacional'),
  ('instituto-de-cordoba-proximo', 'liga-proximo'),
  ('la-union-de-formosa', 'liga-nacional'),
  ('la-union-de-formosa-proximo', 'liga-proximo'),
  ('obera-tenis-club', 'liga-nacional'),
  ('obera-tenis-club-proximo', 'liga-proximo'),
  ('obras-basket', 'liga-nacional'),
  ('obras-basket-proximo', 'liga-proximo'),
  ('olimpico-de-la-banda', 'liga-nacional'),
  ('olimpico-de-la-banda-proximo', 'liga-proximo'),
  ('penarol-de-mar-del-plata', 'liga-nacional'),
  ('penarol-de-mar-del-plata-proximo', 'liga-proximo'),
  ('platense', 'liga-nacional'),
  ('platense-proximo', 'liga-proximo'),
  ('quimsa', 'liga-nacional'),
  ('quimsa-proximo', 'liga-proximo'),
  ('racing-de-chivilcoy', 'liga-nacional'),
  ('racing-de-chivilcoy-proximo', 'liga-proximo'),
  ('regatas-corrientes', 'liga-nacional'),
  ('regatas-corrientes-proximo', 'liga-proximo'),
  ('san-lorenzo-de-almagro', 'liga-nacional'),
  ('san-lorenzo-de-almagro-proximo', 'liga-proximo'),
  ('san-martin-de-corrientes', 'liga-nacional'),
  ('san-martin-de-corrientes-proximo', 'liga-proximo'),
  ('union-de-santa-fe', 'liga-nacional'),
  ('union-de-santa-fe-proximo', 'liga-proximo'),
  ('amancay-de-la-rioja', 'liga-argentina'),
  ('atletico-san-isidro', 'liga-argentina'),
  ('barrio-parque', 'liga-argentina'),
  ('bochas-sport-club', 'liga-argentina'),
  ('centenario-de-venado-tuerto', 'liga-argentina'),
  ('central-entrerriano', 'liga-argentina'),
  ('comunicaciones-de-mercedes', 'liga-argentina'),
  ('club-atletico-estudiantes-de-tucuman', 'liga-argentina'),
  ('ciclista-juninense', 'liga-argentina'),
  ('colon-de-santa-fe', 'liga-argentina'),
  ('deportivo-norte', 'liga-argentina'),
  ('deportivo-viedma', 'liga-argentina'),
  ('el-talar', 'liga-argentina'),
  ('fusion-riojana', 'liga-argentina'),
  ('gimnasia-y-esgrima-de-la-plata', 'liga-argentina'),
  ('hindu-club', 'liga-argentina'),
  ('huracan-las-heras', 'liga-argentina'),
  ('independiente-bbc', 'liga-argentina'),
  ('jujuy-basquet', 'liga-argentina'),
  ('la-union-de-colon', 'liga-argentina'),
  ('lanus', 'liga-argentina'),
  ('pergamino-basquet', 'liga-argentina'),
  ('pico-football-club', 'liga-argentina'),
  ('provincial-de-rosario', 'liga-argentina'),
  ('quilmes-de-mar-del-plata', 'liga-argentina'),
  ('racing-de-avellaneda', 'liga-argentina'),
  ('rivadavia-basquet', 'liga-argentina'),
  ('salta-basket', 'liga-argentina'),
  ('santa-paula-de-galvez', 'liga-argentina'),
  ('sportivo-suardi', 'liga-argentina'),
  ('tomas-de-rocamora', 'liga-argentina'),
  ('union-de-mar-del-plata', 'liga-argentina'),
  ('villa-mitre-de-bahia-blanca', 'liga-argentina'),
  ('villa-san-martin-de-resistencia', 'liga-argentina'),
  ('9-de-julio-de-morteros', 'liga-federal'),
  ('alejandro-korn', 'liga-federal'),
  ('all-boys-de-santa-rosa', 'liga-federal'),
  ('alma-juniors-de-esperanza', 'liga-federal'),
  ('almagro-de-esperanza', 'liga-federal'),
  ('apv', 'liga-federal'),
  ('argentino-de-marcos-juarez', 'liga-federal'),
  ('asociacion-mitre', 'liga-federal'),
  ('atenas-de-la-plata', 'liga-federal'),
  ('atletico-de-rafaela', 'liga-federal'),
  ('atletico-regina', 'liga-federal'),
  ('atletico-sastre', 'liga-federal'),
  ('atletico-tostado', 'liga-federal'),
  ('banda-norte', 'liga-federal'),
  ('belgrano-cultural-y-deportivo', 'liga-federal'),
  ('belgrano-de-san-nicolas', 'liga-federal'),
  ('bochas-sport-club', 'liga-federal'),
  ('capri-de-posadas', 'liga-federal'),
  ('casa-de-padua', 'liga-federal'),
  ('caza-y-pesca', 'liga-federal'),
  ('centro-espanol-de-plottier', 'liga-federal'),
  ('cepa', 'liga-federal'),
  ('ciudad-de-campana', 'liga-federal'),
  ('claridad', 'liga-federal'),
  ('club-atletico-pilar', 'liga-federal'),
  ('concepcion-bb', 'liga-federal'),
  ('cordoba-de-corrientes', 'liga-federal'),
  ('cultural-de-santa-sylvina', 'liga-federal'),
  ('deportivo-plottier', 'liga-federal'),
  ('deportivo-roca', 'liga-federal'),
  ('don-bosco-de-resistencia', 'liga-federal'),
  ('el-carmen-de-perico', 'liga-federal'),
  ('el-ceibo', 'liga-federal'),
  ('estudiantes-de-la-plata', 'liga-federal'),
  ('estudiantes-de-olavarria', 'liga-federal'),
  ('estudiantil-porteno', 'liga-federal'),
  ('ferro-de-general-pico', 'liga-federal'),
  ('gevp', 'liga-federal'),
  ('gimnasia-y-esgrima-de-ituzaingo', 'liga-federal'),
  ('gimnasia-y-esgrima-de-rosario', 'liga-federal'),
  ('gimnasia-y-esgrima-de-santa-fe', 'liga-federal'),
  ('hercules-de-charata', 'liga-federal'),
  ('hindu-club-de-resistencia', 'liga-federal'),
  ('independiente-de-avellaneda', 'liga-federal'),
  ('independiente-de-general-pico', 'liga-federal'),
  ('independiente-de-neuquen', 'liga-federal'),
  ('independiente-de-tandil', 'liga-federal'),
  ('jose-hernandez', 'liga-federal'),
  ('la-armonia-de-colon', 'liga-federal'),
  ('los-indios-de-moreno', 'liga-federal'),
  ('maria-juana', 'liga-federal'),
  ('matienzo-de-cordoba', 'liga-federal'),
  ('midland', 'liga-federal'),
  ('mitre-de-posadas', 'liga-federal'),
  ('montmartre-de-catamarca', 'liga-federal'),
  ('moron', 'liga-federal'),
  ('nautico-avellaneda', 'liga-federal'),
  ('nautico-hacoaj', 'liga-federal'),
  ('olimpia-de-venado-tuerto', 'liga-federal'),
  ('pacifico-de-neuquen', 'liga-federal'),
  ('perfora-de-plaza-huincul', 'liga-federal'),
  ('petrolero-argentino-de-plaza-huincul', 'liga-federal'),
  ('pinocho', 'liga-federal'),
  ('presidente-derqui', 'liga-federal'),
  ('quique-club-de-parana', 'liga-federal'),
  ('racing-de-olavarria', 'liga-federal'),
  ('red-star-de-catamarca', 'liga-federal'),
  ('regatas-de-resistencia', 'liga-federal'),
  ('regatas-de-san-nicolas', 'liga-federal'),
  ('rivadavia-juniors-de-santa-fe', 'liga-federal'),
  ('river-plate', 'liga-federal'),
  ('rosario-central', 'liga-federal'),
  ('san-andres', 'liga-federal'),
  ('san-fernando', 'liga-federal'),
  ('san-lorenzo-de-monte-caseros', 'liga-federal'),
  ('san-martin-de-marcos-juarez', 'liga-federal'),
  ('san-miguel', 'liga-federal'),
  ('sanjustino', 'liga-federal'),
  ('sionista', 'liga-federal'),
  ('somisa-de-san-nicolas', 'liga-federal'),
  ('sportivo-escobar', 'liga-federal'),
  ('sportivo-pilar', 'liga-federal'),
  ('sparta-de-villa-maria', 'liga-federal'),
  ('talleres-de-tafi-viejo', 'liga-federal'),
  ('temperley-de-rosario', 'liga-federal'),
  ('tokio-de-posadas', 'liga-federal'),
  ('tres-de-febrero', 'liga-federal'),
  ('union-de-oncativo', 'liga-federal'),
  ('union-central-de-villa-maria', 'liga-federal'),
  ('union-vecinal-de-munro', 'liga-federal'),
  ('union-y-juventud-de-bandera', 'liga-federal'),
  ('urquiza-de-san-juan', 'liga-federal'),
  ('urquiza-de-santa-elena', 'liga-federal'),
  ('club-tres-de-febrero', 'liga-metropolitana'),
  ('alejandro-korn', 'liga-metropolitana'),
  ('argentino-de-castelar', 'liga-metropolitana'),
  ('asociacion-vecinal-de-pilar', 'liga-metropolitana'),
  ('berazategui', 'liga-metropolitana'),
  ('canuelas-futbol-club', 'liga-metropolitana'),
  ('caza-y-pesca', 'liga-metropolitana'),
  ('cepa', 'liga-metropolitana'),
  ('claridad', 'liga-metropolitana'),
  ('defensores-de-hurlingham', 'liga-metropolitana'),
  ('estudiantil-porteno', 'liga-metropolitana'),
  ('ezeiza', 'liga-metropolitana'),
  ('gimnasia-y-esgrima-de-ituzaingo', 'liga-metropolitana'),
  ('gimnasia-y-esgrima-de-la-plata', 'liga-metropolitana'),
  ('las-heras-de-villa-ballester', 'liga-metropolitana'),
  ('los-andes', 'liga-metropolitana'),
  ('los-indios-de-moreno', 'liga-metropolitana'),
  ('midland', 'liga-metropolitana'),
  ('monte-grande', 'liga-metropolitana'),
  ('moreno-de-quilmes', 'liga-metropolitana'),
  ('moron', 'liga-metropolitana'),
  ('nautico-hacoaj', 'liga-metropolitana'),
  ('nolting', 'liga-metropolitana'),
  ('casa-de-padua', 'liga-metropolitana'),
  ('presidente-derqui', 'liga-metropolitana'),
  ('san-andres', 'liga-metropolitana'),
  ('san-fernando', 'liga-metropolitana'),
  ('san-miguel', 'liga-metropolitana'),
  ('sportivo-escobar', 'liga-metropolitana'),
  ('sportivo-pilar', 'liga-metropolitana'),
  ('union-vecinal-de-munro', 'liga-metropolitana'),
  ('universidad-nacional-de-la-matanza', 'liga-metropolitana'),
  ('bochas-sport-club-femenino', 'liga-femenina'),
  ('chanares-de-james-craik-femenino', 'liga-femenina'),
  ('deportivo-berazategui-femenino', 'liga-femenina'),
  ('el-bigua-femenino', 'liga-femenina'),
  ('el-talar-femenino', 'liga-femenina'),
  ('ferro-carril-oeste-femenino', 'liga-femenina'),
  ('fusion-riojana-femenino', 'liga-femenina'),
  ('gorriones-de-rio-cuarto-femenino', 'liga-femenina'),
  ('hindu-club-de-cordoba-femenino', 'liga-femenina'),
  ('independiente-de-neuquen-femenino', 'liga-femenina'),
  ('instituto-de-cordoba-femenino', 'liga-femenina'),
  ('lanus-femenino', 'liga-femenina'),
  ('nautico-sportivo-avellaneda-femenino', 'liga-femenina'),
  ('obras-basket-femenino', 'liga-femenina'),
  ('quimsa-femenino', 'liga-femenina'),
  ('tomas-de-rocamora-femenino', 'liga-femenina'),
  ('san-jose-de-mendoza-femenino', 'liga-femenina'),
  ('union-florida-femenino', 'liga-femenina')
) as v(team_slug, league_slug)
join public.teams t on t.slug = v.team_slug
join public.leagues l on l.slug = v.league_slug
on conflict do nothing;

-- Backfill matches.league_id from the free-text competition column.
update public.matches m
set league_id = l.id
from (values
  ('liga federal', 'liga-federal'),
  ('liga nacional', 'liga-nacional'),
  ('liga endesa (acb)', 'liga-endesa-acb'),
  ('lpb fem ecuador', 'lpb-fem-ecuador'),
  ('liga argentina', 'liga-argentina'),
  ('exterior', 'exterior'),
  ('amistosos', 'amistosos'),
  ('euroliga', 'euroliga'),
  ('liga femenina', 'liga-femenina'),
  ('liga italiana (lba)', 'liga-italiana-lba'),
  ('nbb', 'nbb'),
  ('interligas ldb', 'interligas-ldb'),
  ('liga proximo', 'liga-proximo'),
  ('liga próximo', 'liga-proximo'),
  ('3x3', '3x3'),
  ('liga chery', 'liga-chery'),
  ('liga nacional / liga próximo', 'liga-nacional'),
  ('liga nacional / liga proximo', 'liga-nacional'),
  ('pre metropolina', 'pre-metropolitana'),
  ('pre metropolitana', 'pre-metropolitana')
) as map(raw_competition, league_slug)
join public.leagues l on l.slug = map.league_slug
where m.league_id is null
  and lower(trim(m.competition)) = map.raw_competition;
